package au.wow.ngbomain.pages;

import java.awt.AWTException;
import java.awt.Robot;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Collections;
import java.util.List;
import org.openqa.selenium.By;
import org.openqa.selenium.Keys;
import org.openqa.selenium.Point;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.interactions.internal.Coordinates;
import org.openqa.selenium.internal.Locatable;
import au.wow.ngbo.utils.BasePage;
import au.wow.ngbomain.objects.OnlineBookingobjects;
//import au.wow.ngbomain.tests.OnlineBookingTests;

import com.relevantcodes.extentreports.ExtentTest;


public class LaybyPages extends BasePage{
	
	
	public void setDriver(WebDriver driver){
		this.driver=driver;
	}
	
	//DailyStockCheckReportObjects objDscReport;
/*	
	public void clickOnDsctReport(DSCandPLUReportObjects objDscReport,WebDriver driver) throws AWTException{
//		waitForJSandJQueryToLoad(driver);;
		waitFor(1);
		Point coordinates = objDscReport.report.getLocation();
		Robot robot = new Robot();
		robot.mouseMove(coordinates.getX(),coordinates.getY()+100);
		
		Actions action = new Actions(driver);
		action.moveToElement(objDscReport.report).click().build().perform();	
		waitFor(1);
		
		Actions action1 = new Actions(driver);
		action1.moveToElement(objDscReport.stockManagement).click().build().perform();	
		waitFor(1);
				
		
		Actions action2 = new Actions(driver);
		action2.moveToElement(objDscReport.dailyStockCheckReport).click().build().perform();
		waitFor(1);
		robot.mouseMove(5,5);
	
	}
	
	public void clickOnPLUReport(DSCandPLUReportObjects objDscReport,WebDriver driver) throws AWTException{
//		waitForJSandJQueryToLoad(driver);;
		waitFor(1);
		Point coordinates = objDscReport.report.getLocation();
		Robot robot = new Robot();
		robot.mouseMove(coordinates.getX(),coordinates.getY()+100);
		
		Actions action = new Actions(driver);
		action.moveToElement(objDscReport.report).click().build().perform();	
		waitFor(1);
		
		Actions action1 = new Actions(driver);
		action1.moveToElement(objDscReport.stockManagement).click().build().perform();	
		waitFor(1);
				
		Actions action2 = new Actions(driver);
		action2.moveToElement(objDscReport.PLUReport).click().build().perform();
		waitFor(1);
		robot.mouseMove(5,5);
	
	}
	
	public void verifyDSCReportAllDepartment(DSCandPLUReportObjects objDscReport,int countDB,WebDriver driver) throws IOException
	{
		
		if(!(isEnabled(objDscReport.optionSelectAll)))
		  click(objDscReport.optionSelectAll);
		waitForJSandJQueryToLoad(driver);;
		click(objDscReport.generateReportBtn);
		waitForJSandJQueryToLoad(driver);;
		String applCount = getText(objDscReport.reportcount);
		String countDBStringValue = String.valueOf(countDB);
		
		if(applCount.equals(countDBStringValue))
			
			htmlToExtent(cName,mName,extLogger,driver, "The No of records generated by the report is correct;"+applCount+";"+countDBStringValue+";Pass");
			//Report_AddStep("testcase", "The No of records generated by the report is correct",applCount ,countDBStringValue , "Pass");
		else
			htmlToExtent(cName,mName,extLogger,driver, "The No of records generated by the report is correct;"+applCount+";"+countDBStringValue+";Fail");
		//Report_AddStep("testcase","The No of records generated by the report is incorrect",applCount ,countDBStringValue , "Fail");
		
		//VerifyPrintButton
		String winHandleBefore = driver.getWindowHandle();
		waitFor(2);
		click(objDscReport.printBtn);
		waitFor(2);
		
		for(String winHandle : driver.getWindowHandles()){
		    driver.switchTo().window(winHandle);
		}
		driver.close();
		driver.switchTo().window(winHandleBefore);
		waitForJSandJQueryToLoad(driver);;
		htmlToExtent(cName,mName,extLogger,driver, "The Print pdf is generated successfully;;;Pass");
		//Report_AddStep("testcase","The Print pdf is generated successfully","" ,"" , "PASS");
		waitFor(3);
		driver.findElement(By.cssSelector("body")).sendKeys(Keys.CONTROL + "w");
		htmlToExtent(cName,mName,extLogger,driver, "The Print pdf is closed successfully;;;Pass");
		//Report_AddStep("testcase","The Print pdf is closed successfully","" ,"" , "PASS");
		
		//ArticleColumn
		click(objDscReport.articleColumn);
		waitForJSandJQueryToLoad(driver);;
		sortNumberListAscending("Article Number",objDscReport.articleno_sort ,driver);
		click(objDscReport.articleColumn);
		waitForJSandJQueryToLoad(driver);;
		sortNumberListDescending("Article Number",objDscReport.articleno_sort ,driver);
	     
	   //DescriptionColumn
		click(objDscReport.descColumn);
		waitForJSandJQueryToLoad(driver);;
		sortStringListAscending("Description",objDscReport.articleDesc_sort ,driver);
		click(objDscReport.descColumn);
		waitForJSandJQueryToLoad(driver);;
		sortStringListDescending("Description",objDscReport.articleDesc_sort ,driver);
		
		//OM Column
		 click(objDscReport.OMColumn);
		 waitForJSandJQueryToLoad(driver);;
		 sortNumberListAscending("OM",objDscReport.articleOM_sort,driver);
		 click(objDscReport.OMColumn);
		 waitForJSandJQueryToLoad(driver);;
		 sortNumberListDescending("OM",objDscReport.articleOM_sort,driver);
		 
		//SOH Column
		 click(objDscReport.sohColumn);
		 waitForJSandJQueryToLoad(driver);;
		 sortSOHAscending("SOH",objDscReport.articleSOH_sort,driver);
		 click(objDscReport.sohColumn);
		 waitForJSandJQueryToLoad(driver);;
		 sortSOHDescending("SOH",objDscReport.articleSOH_sort,driver);
	
//		//SIT Column (Commented as it doesn't follow a pattern in application
//		 click(objDscReport.sitColumn);
//		 waitForJSandJQueryToLoad(driver);;
//		 sortStringListAscending("SIT",objDscReport.articleSIT_sort,driver);
//	     click(objDscReport.sitColumn);
//		 waitForJSandJQueryToLoad(driver);;
//		 sortStringListDescending("SIT",objDscReport.articleSIT_sort,driver);
		 	
		//LTO Location Column
		 click(objDscReport.ltoLocationColumn);
		 waitForJSandJQueryToLoad(driver);;
		 sortStringListAscending("LTO Location",objDscReport.articleLTO_sort,driver);
		 click(objDscReport.ltoLocationColumn);
		 waitForJSandJQueryToLoad(driver);;
		 sortStringListDescending("LTO Location",objDscReport.articleLTO_sort,driver);
				
		//Display Location Column
		 click(objDscReport.displayColumn);
		 waitForJSandJQueryToLoad(driver);;
		 sortStringListAscending("Display Location",objDscReport.articleDisplay_sort,driver);
		 click(objDscReport.displayColumn);
		 waitForJSandJQueryToLoad(driver);;
		 sortStringListDescending("Display Location",objDscReport.articleDisplay_sort,driver);
			
		//Reason Code Column
		 htmlToExtent(cName,mName,extLogger,driver, "The Reason Code has the value : "+getText(objDscReport.reasonCodeFirstValue)+";;;Pass");
		//Report_AddStep("testcase", "The Reason Code has the value : " +getText(objDscReport.reasonCodeFirstValue),"" ,"" , "Pass");
	      
		 click(objDscReport.reasonCodeColumn);
		 waitForJSandJQueryToLoad(driver);;
		 sortStringListAscending("Reason Code",objDscReport.articleReason_sort,driver);
		 htmlToExtent(cName,mName,extLogger,driver, "The Reason Code has the value : "+getText(objDscReport.reasonCodeFirstValue)+";;;Pass");
		//Report_AddStep("testcase", "The Reason Code has the value : "+getText(objDscReport.reasonCodeFirstValue) ,"" ,"" , "Pass");
	     	 
		 click(objDscReport.reasonCodeColumn);
		 waitForJSandJQueryToLoad(driver);;
		 sortStringListDescending("Display Location",objDscReport.articleReason_sort,driver);
		 htmlToExtent(cName,mName,extLogger,driver, "The Reason Code has the value : "+getText(objDscReport.reasonCodeFirstValue)+";;;Pass");
		 //Report_AddStep("testcase", "The Reason Code has the value : "+getText(objDscReport.reasonCodeFirstValue) ,"" ,"" , "Pass");

		
	}*/
	


}

